export const SEED_LABORATORIES = [
  {
    name: 'BIS Central Laboratory',
    labCode: 'BIS-LAB-001',
    address: 'Plot No. 20/9, Site IV, Sahibabad Industrial Area',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    pincode: '201010',
    contactPerson: 'Director (Lab Operations)',
    contactEmail: 'cl@bis.gov.in',
    contactPhone: '+91-120-4177100',
    recognitionStatus: 'RECOGNIZED',
    validUpTo: '2030-12-31',
    accreditationBody: 'NABL & BIS Central Reference Laboratory',
    recognizedStandards: ['IS 17526', 'IS 14454', 'IS 10500', 'IS 14543', 'IS 1786', 'IS 269', 'IS 16046', 'IS 302'],
    testingCapabilities: ['Chemical Analysis', 'Mechanical & Tensile Testing', 'Microbiological Testing', 'Electrical Safety', 'Thermal Insulation Performance'],
    isNablAccredited: true,
    isBisRecognized: true,
    latitude: 28.6692,
    longitude: 77.3489,
    sourceUrl: 'https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/labs/cl-sahibabad',
    lastUpdatedDate: '2024-02-01'
  },
  {
    name: 'National Test House (Western Region)',
    labCode: 'NTH-WR-002',
    address: 'Plot F-10, MIDC, Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400093',
    contactPerson: 'Scientist-in-Charge',
    contactEmail: 'nthwr-mumbai@nic.in',
    contactPhone: '+91-22-28327701',
    recognitionStatus: 'RECOGNIZED',
    validUpTo: '2028-09-30',
    accreditationBody: 'NABL (ISO/IEC 17025)',
    recognizedStandards: ['IS 17526', 'IS 14454', 'IS 1786', 'IS 269', 'IS 10500', 'IS 14543'],
    testingCapabilities: ['Metals Chemical Spectrometry', 'Tensile & Bend Testing', 'Cement Physical Tests', 'Water Pesticide Residue'],
    isNablAccredited: true,
    isBisRecognized: true,
    latitude: 19.1136,
    longitude: 72.8697,
    sourceUrl: 'https://nth.gov.in',
    lastUpdatedDate: '2024-01-15'
  },
  {
    name: 'TUV Rheinland India Testing Laboratory',
    labCode: 'TUV-IN-003',
    address: 'Electronics City Phase 1, Hosur Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560100',
    contactPerson: 'Head of Electrical & Battery Testing',
    contactEmail: 'info-india@tuv.com',
    contactPhone: '+91-80-46498000',
    recognitionStatus: 'RECOGNIZED',
    validUpTo: '2027-11-30',
    accreditationBody: 'NABL (ISO/IEC 17025) & BIS Recognized',
    recognizedStandards: ['IS 16046', 'IS 302', 'IS 1293', 'IS 17526'],
    testingCapabilities: ['Lithium Battery Safety Chamber', 'Electrical Appliance Insulation', 'Environmental Altitude Simulation', 'Thermal Shock'],
    isNablAccredited: true,
    isBisRecognized: true,
    latitude: 12.8399,
    longitude: 77.6770,
    sourceUrl: 'https://www.tuv.com/india',
    lastUpdatedDate: '2024-02-10'
  },
  {
    name: 'Reliable Analytical Laboratories Pvt Ltd',
    labCode: 'RAL-IN-004',
    address: 'Reliable House, Thane-Belapur Road, Turbhe',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    pincode: '400705',
    contactPerson: 'Technical Director',
    contactEmail: 'contact@reliablelabs.org',
    contactPhone: '+91-22-67891234',
    recognitionStatus: 'RECOGNIZED',
    validUpTo: '2028-06-30',
    accreditationBody: 'NABL & BIS Recognized',
    recognizedStandards: ['IS 10500', 'IS 14543', 'IS 17526', 'IS 14454'],
    testingCapabilities: ['Water Chemical & Trace Heavy Metals', 'Microbiological Pathogen Testing', 'Food Contact Material Leaching Test', 'Corrosion Resistance'],
    isNablAccredited: true,
    isBisRecognized: true,
    latitude: 19.0760,
    longitude: 73.0135,
    sourceUrl: 'https://reliablelabs.org',
    lastUpdatedDate: '2024-01-20'
  },
  {
    name: 'SGS India Testing Facility',
    labCode: 'SGS-IN-005',
    address: '28 B, Udyog Vihar Phase IV',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122016',
    contactPerson: 'Lead Materials Specialist',
    contactEmail: 'sgs.india@sgs.com',
    contactPhone: '+91-124-6787600',
    recognitionStatus: 'RECOGNIZED',
    validUpTo: '2029-03-31',
    accreditationBody: 'NABL & BIS Recognized',
    recognizedStandards: ['IS 17526', 'IS 14454', 'IS 1786', 'IS 302'],
    testingCapabilities: ['Thermal Retention Test', 'Spectrometric Grade Verification', 'Tensile Stress Testing', 'Flammability & Glow Wire'],
    isNablAccredited: true,
    isBisRecognized: true,
    latitude: 28.4975,
    longitude: 77.0782,
    sourceUrl: 'https://sgs.com',
    lastUpdatedDate: '2024-02-18'
  }
];
