export declare const SEED_USERS: {
    email: string;
    passwordHash: string;
    fullName: string;
    role: any;
    organization: string;
    designation: string;
    preferredLanguage: string;
}[];
export declare const SEED_STANDARDS: ({
    standardNumber: string;
    title: string;
    year: number;
    department: string;
    division: string;
    status: any;
    scope: string;
    abstract: string;
    keywords: string[];
    isMandatory: boolean;
    qcoNotificationNumber: string;
    qcoDate: string;
    sourceUrl: string;
    publicationDate: string;
    lastUpdatedDate: string;
} | {
    standardNumber: string;
    title: string;
    year: number;
    department: string;
    division: string;
    status: any;
    scope: string;
    abstract: string;
    keywords: string[];
    isMandatory: boolean;
    qcoNotificationNumber: null;
    qcoDate: null;
    sourceUrl: string;
    publicationDate: string;
    lastUpdatedDate: string;
})[];
export declare const SEED_SCHEMES: {
    schemeType: any;
    name: string;
    code: string;
    description: string;
    applicability: string;
    applicableSectors: string[];
    mandatoryProductCategories: string[];
    keySteps: {
        stepNumber: number;
        title: string;
        description: string;
        responsibleParty: string;
        estimatedDuration: string;
    }[];
    requiredDocuments: string[];
    feeStructureSummary: string;
    surveillanceFrequency: string;
    validityPeriod: string;
    officialGuidelineUrl: string;
}[];
export declare const SEED_LABORATORIES: {
    name: string;
    labCode: string;
    address: string;
    city: string;
    state: string;
    pincode: string;
    contactPerson: string;
    contactEmail: string;
    contactPhone: string;
    recognitionStatus: string;
    validUpTo: string;
    accreditationBody: string;
    recognizedStandards: string[];
    testingCapabilities: string[];
    isNablAccredited: boolean;
    isBisRecognized: boolean;
    latitude: number;
    longitude: number;
    sourceUrl: string;
    lastUpdatedDate: string;
}[];
export declare const SEED_HALLMARKING_CENTRES: {
    centreName: string;
    centreCode: string;
    address: string;
    city: string;
    state: string;
    pincode: string;
    contactEmail: string;
    contactPhone: string;
    recognizedMetals: string[];
    recognitionStatus: string;
    validUpTo: string;
    sourceUrl: string;
}[];
//# sourceMappingURL=seed-data.d.ts.map